### PR TITLE
Improve figure size and show argument in viz functions

### LINKED ISSUE #97: [ENH] Improve default figure size when plotting cluster centers
When you plot cluster centers, the figure has a lot of 'white' space above and below. It messes up a bit the render of the tutorials, e.g. https://pycrostates.readthedocs.io/en/latest/generated/auto_tutorials/clustering/plot_modK.html#sphx-glr-generated-auto-tutorials-clustering-plot-modk-py

The default figure is created here https://github.com/vferat/pycrostates/blob/c6af5bd6319ac601b317b48b299f46754ad09adf/pycrostates/viz/cluster_centers.py#L68-L70

It should be updated to create a figure with a more appropriate size.

### LINKED ISSUE #126: `plot_raw_segmentation` has not a `show` parameter
`plot_raw_segmentation` has not a `show` parameter 

https://github.com/vferat/pycrostates/blob/588c644eab08c83cd4a1a67b2e01f7adf475aee0/pycrostates/viz/segmentation.py#L100

### PR DESCRIPTION
**Pull request by mscheltienne**
Closes #97 
Closes #126 

Try to define a better figsize for cluster center plots.
Move the show argument outsides of the kwargs of the viz functions to make it explicit.
Fix ruff configuration which now requires separate `tools.ruff.lint` and `tools.ruff.format` section.
Enable ruff lint rules `A` and `B`.

### CODE REVIEW

**Comment by mscheltienne** [comment]
Screenshot from 2024-02-14 14-45-38

Figsize looks better.
@vferat merge if happy. Also, OK to cut a new release with the recent additions?

**Comment by vferat** [comment]
Renders are way better this way ! Thanks

Any reason not to include `show = plt.isinteractive() if show is None else show` in  a `_check_show`  function ?

```
def _check_show(show):
    """Check show parameter."""
    _check_type(show, (bool, None), "show")
    show = plt.isinteractive() if show is None else show
    return show
```

**Comment by mscheltienne** [comment]
Done as `_ensure_valid_show`, I renamed the function because I make the difference between:
- `_check_xxx` which returns None
- `_ensure_xxx` which returns a validated object of `xxx`

**Comment by vferat** [comment]
Perfect !
LGTM, and I agree that a release could be nice, a minor version `0.4.2` maybe ?

**Comment by mscheltienne** [comment]
I would say 0.5.0
Nomenclature is major.minor.bugfix and I would not consider the new features as part of a bug fix release ;)

**Pull request merged**
