### PR TITLE
[MNT] Unpin matplotlib

### PR DESCRIPTION
**Pull request by mscheltienne**
Following #77, I've pin the version of matplotlib. 
It's not the best idea as the pin is very strict with only the latest version. It may results in conflicts with environments with many packages.

Usually, we should aim to support 4/5 minor version of our dependencies. In this PR, I reverted some of the changes from #77 to make sure older versions of matplotlib would still work.

### CODE REVIEW

**Comment by vferat** [comment]
It will make it easier to maintain the code if we implement a  `check_cmap` function, don't you think ?

**Comment by mscheltienne** [comment]
Definitely, I'll edit the PR.

**Comment by mscheltienne** [comment]
@vferat Have a look :)

**Comment by mscheltienne** [comment]
@vferat Good to merge?

**Pull request merged**
